site_name: Site for students from group P3123
site_url: https://ngoctruong22.github.io/demo702/
nav:
    - Home: index.md
    - About: about.md
theme:
    name: material
    hightlighjs: true
    font:
      text: Google Font
      code: Google Font Mono
    hljs_languages:
      - yaml
      - rust
